CREATE TABLE ARTICLES
(
    ID              VARCHAR(50),
    TITLE        VARCHAR(100),
    CONTENT        VARCHAR(100),
    AUTHOR_ID           VARCHAR(100),
    AUTHOR_NAME            VARCHAR(100),
    CREATED_AT      TIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    PRIMARY KEY (ID)
);