spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/handsondb/article;AUTO_SERVER=TRUE   #여러 Application에서 같은 DB를 바라볼수 있다
    username: sa
    password: sa
  jpa:
    show-sql: true
  flyway:
    locations: ["classpath:db/migration", "classpath:db/sample-data"]

server:
  port: 0
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.web: debug