CREATE TABLE ACCOUNTS
(
    ID              VARCHAR(50),
    USERNAME        VARCHAR(100),
    PASSWORD        VARCHAR(100),
    EMAIL           VARCHAR(100),
    NAME            VARCHAR(100),
    ARTICLE_COUNT   INTEGER,
    CREATED_AT      TIMESTAMP,
    PRIMARY KEY (ID)
);