INSERT INTO ACCOUNTS
(ID, USERNAME, PASSWORD, EMAIL, NAME, ARTICLE_COUNT, CREATED_AT)
VALUES
('TEST-ACCOUNTS-001', 'hong@mz.co.kr', '$2a$10$zK9Ie.IOWY8xHvf5.4JBRemmkD9MCuMJBi5B1X3Wr9RxBWwlbG16u', 'josh@nomad-coders.io', '조쉬홍', 0, NOW())
;